### PR TITLE
App structure improvements

### PR DESCRIPTION
**Pull request by ianlofs**
This is a major overhaul of the over all app structure. Please test thoroughly.  Deleted a lot of unused code as well. Hopefully this makes things more intelligible.

### CODE REVIEW

**Comment by jessebrennan** [comment]
I've noticed some typos in the readme; should I change those here or should I change them in master?

Also [this](https://github.com/seadsystem/website/tree/app-structure-improvements#the-rest-of-these-instructions-are-the-same-on-osx-and-ubuntu) section is not completely accurate for me.

also when setting up your PostgreSQL db shouldn't port be 5432 (default psql port)?

also shouldn't we add instructions for installing psycopg2? or @ianlofs did you get it running withough installing psycopg2?

I will update readme, I just want confirmation on these changes.

**Comment by ianlofs** [comment]
@leafmeal the postgres port shouldnt matter. it uses the default port already. if the psycopg2 is needed then yeah add that to the readme its just  `pip3 install pyscop2`. I cant remember is i had to install it.

**Comment by SydBal** [comment]
This satisfies me. For now.

**Comment by jessebrennan** [comment]
Crashes when trying to register a device that already exists (the device_id already exists). Repeated names are fine. I imagine this is because device_id is the primary key for the model. We just need to catch the exception and give an error message.

**Pull request merged**
